"""Gate M gold questions. Locators must appear verbatim in gold_document.PAGES."""
from __future__ import annotations

from typing import Any

# Categories match the Gate M brief.
SIMPLE_LOCAL = "SIMPLE_LOCAL"
LEXICAL_VARIATION = "LEXICAL_VARIATION"
NUMERIC = "NUMERIC"
EXCEPTION = "EXCEPTION"
TABLE = "TABLE"
MULTI_HOP = "MULTI_HOP"
GLOBAL = "GLOBAL"
NEGATIVE = "NEGATIVE"


def _q(
    qid: str,
    question: str,
    category: str,
    *,
    answerable: bool,
    gold_answer: str,
    decisive: list[dict[str, Any]],
    supporting: list[dict[str, Any]] | None = None,
    aliases: list[str] | None = None,
    must_all: list[str] | None = None,
    notes: str = "",
    false_attractors: list[str] | None = None,
) -> dict[str, Any]:
    return {
        "question_id": qid,
        "question": question,
        "category": category,
        "answerable": answerable,
        "gold_answer": gold_answer,
        "gold_answer_aliases": aliases or [],
        "gold_must_all": must_all or [],
        "decisive_evidence": decisive,
        "supporting_evidence": supporting or [],
        "false_attractors": false_attractors or [],
        "notes": notes,
    }


def _span(page: int, locator: str, importance: str = "decisive") -> dict[str, Any]:
    return {"page": page, "text_or_locator": locator, "importance": importance}


QUESTIONS: list[dict[str, Any]] = [
    # --- A. SIMPLE_LOCAL ---
    _q(
        "M01",
        "What is the agreement ID?",
        SIMPLE_LOCAL,
        answerable=True,
        gold_answer="BEN-GOLD-SA-2026-001",
        decisive=[_span(1, "BEN-GOLD-SA-2026-001")],
        notes="Title-page identifier.",
    ),
    _q(
        "M02",
        "Who is the buyer named in the agreement?",
        SIMPLE_LOCAL,
        answerable=True,
        gold_answer="Coastal Works Ltd",
        decisive=[_span(1, "Coastal Works Ltd")],
    ),
    _q(
        "M03",
        "Who is the supplier named in the agreement?",
        SIMPLE_LOCAL,
        answerable=True,
        gold_answer="Northwind Insulation Ltd",
        decisive=[_span(1, "Northwind Insulation Ltd")],
    ),
    _q(
        "M04",
        "What is the effective date of the agreement?",
        SIMPLE_LOCAL,
        answerable=True,
        gold_answer="1 March 2026",
        aliases=["March 1, 2026", "1 March 2026"],
        decisive=[_span(1, "Effective date: 1 March 2026")],
    ),
    _q(
        "M05",
        "What is the named delivery street address in Netanya?",
        SIMPLE_LOCAL,
        answerable=True,
        gold_answer="12 HaMelacha Street",
        decisive=[_span(2, "DELIVERY-PLACE-HAMELACHA-12")],
        supporting=[_span(2, "12 HaMelacha Street", "supporting")],
    ),
    _q(
        "M06",
        "What are the site offload hours?",
        SIMPLE_LOCAL,
        answerable=True,
        gold_answer="07:00 to 15:00",
        aliases=["Sunday to Thursday 07:00 to 15:00"],
        decisive=[_span(15, "OFFLOAD-WINDOW-0715")],
        notes="Late page. Prefix path is expected to miss this.",
    ),
    _q(
        "M07",
        "Who provides the forklift for offload?",
        SIMPLE_LOCAL,
        answerable=True,
        gold_answer="Forklift is provided by Buyer",
        aliases=["provided by Buyer"],
        decisive=[_span(15, "Forklift is provided by Buyer")],
        notes="Late page.",
    ),
    _q(
        "M08",
        "What is the supplier commercial contact name?",
        SIMPLE_LOCAL,
        answerable=True,
        gold_answer="Dana Levi",
        decisive=[_span(10, "CONTACT-DANA-LEVI")],
    ),
    # --- B. LEXICAL_VARIATION ---
    _q(
        "M09",
        "Where must the goods be delivered?",
        LEXICAL_VARIATION,
        answerable=True,
        gold_answer="12 HaMelacha Street, Netanya",
        aliases=["12 HaMelacha Street"],
        decisive=[_span(2, "named delivery place is 12 HaMelacha Street")],
        notes="Question avoids the words 'named delivery place'.",
    ),
    _q(
        "M10",
        "What fire rating paperwork must accompany the first shipment?",
        LEXICAL_VARIATION,
        answerable=True,
        gold_answer="EN 13501-1 class A1",
        aliases=["fire-classification certificate to EN 13501-1 class A1"],
        decisive=[_span(6, "FIRE-CERT-EN13501-A1")],
    ),
    _q(
        "M11",
        "How long after noticing a defect may the buyer still send a warranty claim?",
        LEXICAL_VARIATION,
        answerable=True,
        gold_answer="10 business days",
        decisive=[_span(7, "10 business days of discovery")],
    ),
    _q(
        "M12",
        "What is the maximum weight allowed on one pallet?",
        LEXICAL_VARIATION,
        answerable=True,
        gold_answer="1.2 tonnes",
        aliases=["1.2 tonnes per pallet"],
        decisive=[_span(11, "PALLET-MAX-1P2-TONNES")],
    ),
    _q(
        "M13",
        "Does silence after delivery count as accepting the goods?",
        LEXICAL_VARIATION,
        answerable=True,
        gold_answer="Silence is not deemed acceptance",
        aliases=["not deemed acceptance"],
        decisive=[_span(12, "Silence is not deemed acceptance")],
    ),
    _q(
        "M14",
        "How can a party end the contract after a serious breach if the other side does not fix it?",
        LEXICAL_VARIATION,
        answerable=True,
        gold_answer="14 days cure notice",
        aliases=["terminate for material breach after 14 days cure notice"],
        decisive=[_span(18, "CURE-14-DAYS")],
        notes="Late page + paraphrase of termination.",
    ),
    # --- C. NUMERIC ---
    _q(
        "M15",
        "What is the declared lambda of the primary product?",
        NUMERIC,
        answerable=True,
        gold_answer="0.035 W/mK",
        aliases=["0.035"],
        decisive=[_span(3, "SPEC-LAMBDA-0035")],
    ),
    _q(
        "M16",
        "What is the nominal density of the mineral wool boards?",
        NUMERIC,
        answerable=True,
        gold_answer="100 kg/m3",
        decisive=[_span(3, "Nominal density: 100 kg/m3")],
    ),
    _q(
        "M17",
        "What contract quantity is stated for the primary product?",
        NUMERIC,
        answerable=True,
        gold_answer="10,000 square metres",
        aliases=["10,000", "10000"],
        decisive=[_span(3, "Contract quantity: 10,000 square metres")],
    ),
    _q(
        "M18",
        "What is the standard lead time after a valid purchase order?",
        NUMERIC,
        answerable=True,
        gold_answer="21 calendar days",
        decisive=[_span(2, "21 calendar days after a valid purchase order")],
    ),
    _q(
        "M19",
        "What product liability insurance amount is required per occurrence?",
        NUMERIC,
        answerable=True,
        gold_answer="ILS 8,000,000",
        aliases=["8,000,000"],
        decisive=[_span(9, "INSURANCE-ILS-8000000")],
    ),
    _q(
        "M20",
        "What VAT rate is added on invoices?",
        NUMERIC,
        answerable=True,
        gold_answer="17 percent",
        aliases=["17%"],
        decisive=[_span(4, "VAT is 17 percent")],
    ),
    _q(
        "M21",
        "How long does confidentiality survive after termination?",
        NUMERIC,
        answerable=True,
        gold_answer="3 years",
        decisive=[_span(18, "Confidentiality survives for 3 years")],
        notes="Late page.",
    ),
    # --- D. EXCEPTION ---
    _q(
        "M22",
        "What is the main rule about partial shipments?",
        EXCEPTION,
        answerable=True,
        gold_answer="shall not make partial shipments",
        aliases=["Each purchase order ships complete"],
        decisive=[_span(5, "MAIN-RULE-NO-PARTIAL-SHIP")],
        notes="Main rule only; exception is on page 14.",
    ),
    _q(
        "M23",
        "Are any partial shipments allowed despite the main completeness rule?",
        EXCEPTION,
        answerable=True,
        gold_answer="emergency orders of 200 m2 or less may ship partial within 48 hours",
        aliases=["EXCEPTION-PARTIAL-SHIP-48H"],
        decisive=[_span(14, "EXCEPTION-PARTIAL-SHIP-48H")],
        supporting=[_span(5, "MAIN-RULE-NO-PARTIAL-SHIP", "supporting")],
        notes="Decisive exception is after the prefix cutoff.",
    ),
    _q(
        "M24",
        "What is the maximum size of an emergency order that may ship partial?",
        EXCEPTION,
        answerable=True,
        gold_answer="200 m2",
        aliases=["200 m2 or less"],
        decisive=[_span(14, "emergency orders of 200 m2 or less")],
    ),
    _q(
        "M25",
        "Does the emergency partial-shipment exception apply to MW-100?",
        EXCEPTION,
        answerable=True,
        gold_answer="does not apply to MW-100",
        aliases=["This exception does not apply to MW-100"],
        decisive=[_span(14, "This exception does not apply to MW-100")],
    ),
    _q(
        "M26",
        "How fast may an emergency partial shipment leave once the exception applies?",
        EXCEPTION,
        answerable=True,
        gold_answer="48 hours",
        decisive=[_span(14, "may ship partial within 48 hours")],
    ),
    # --- E. TABLE ---
    _q(
        "M27",
        "What is the unit price in ILS for SKU MW-50?",
        TABLE,
        answerable=True,
        gold_answer="42.50",
        decisive=[_span(4, "PRICE-TABLE-MW50-4250")],
        supporting=[_span(4, "MW-50 | Mineral wool board | 50 mm | 42.50", "supporting")],
    ),
    _q(
        "M28",
        "What is the unit price in ILS for SKU MW-80?",
        TABLE,
        answerable=True,
        gold_answer="61.00",
        decisive=[_span(4, "MW-80 | Mineral wool board | 80 mm | 61.00")],
    ),
    _q(
        "M29",
        "What is the unit price in ILS for SKU MW-100?",
        TABLE,
        answerable=True,
        gold_answer="74.25",
        decisive=[_span(4, "MW-100 | Mineral wool board | 100 mm | 74.25")],
    ),
    _q(
        "M30",
        "What is the standard lead time in days for Haifa District?",
        TABLE,
        answerable=True,
        gold_answer="18",
        aliases=["18 | 9", "Haifa District | 18"],
        decisive=[_span(16, "LEADTIME-TABLE-REGIONS")],
        supporting=[_span(16, "Haifa District | 18 | 9", "supporting")],
        notes="Late table.",
    ),
    _q(
        "M31",
        "What is the expedite lead time in days for Southern District?",
        TABLE,
        answerable=True,
        gold_answer="Southern District | 25 | 12",
        aliases=["25 | 12"],
        decisive=[_span(16, "Southern District | 25 | 12")],
        notes="Late table.",
    ),
    _q(
        "M32",
        "What is the standard lead time in days for Tel Aviv District?",
        TABLE,
        answerable=True,
        gold_answer="Tel Aviv District | 14 | 7",
        aliases=["14 | 7"],
        decisive=[_span(16, "Tel Aviv District | 14 | 7")],
        notes="Late table.",
    ),
    # --- F. MULTI_HOP ---
    _q(
        "M33",
        "Using the contract quantity and the MW-50 unit price, what is the exclusive-of-VAT goods value in ILS?",
        MULTI_HOP,
        answerable=True,
        gold_answer="425000",
        aliases=["425,000", "10,000 * 42.50"],
        decisive=[
            _span(3, "Contract quantity: 10,000 square metres"),
            _span(4, "MW-50 | Mineral wool board | 50 mm | 42.50"),
        ],
        notes="Requires quantity (p3) and price (p4). Extractive string match may miss computed product.",
    ),
    _q(
        "M34",
        "If MW-80 is substituted for MW-50, what quantity still applies unless a change order says otherwise?",
        MULTI_HOP,
        answerable=True,
        gold_answer="10,000 square metres",
        aliases=["10,000"],
        decisive=[
            _span(17, "SUBSTITUTION-MW80-QTY"),
            _span(3, "Contract quantity: 10,000 square metres"),
        ],
        notes="Quantity restated on page 17; original on page 3.",
    ),
    _q(
        "M35",
        "What unit price applies to extra MW-50 on a change order without expedite?",
        MULTI_HOP,
        answerable=True,
        gold_answer="42.50",
        decisive=[
            _span(13, "Extra MW-50 uses the Article 3 table price"),
            _span(4, "MW-50 | Mineral wool board | 50 mm | 42.50"),
        ],
    ),
    _q(
        "M36",
        "What extra percent is added to the table price when extra MW-50 is needed in under 10 days?",
        MULTI_HOP,
        answerable=True,
        gold_answer="8 percent",
        aliases=["8%"],
        decisive=[_span(13, "EXPEDITE-PLUS-8-PERCENT")],
        supporting=[_span(4, "PRICE-TABLE-MW50-4250", "supporting")],
    ),
    _q(
        "M37",
        "What fire certificate class is required, and which ISO management certificate is required?",
        MULTI_HOP,
        answerable=True,
        gold_answer="EN 13501-1 class A1 and ISO 9001",
        aliases=["EN 13501-1 class A1", "ISO 9001"],
        must_all=["EN 13501-1 class A1", "ISO 9001"],
        decisive=[
            _span(6, "EN 13501-1 class A1"),
            _span(6, "ISO 9001 certificate is required"),
        ],
        notes="Two facts on the same page.",
    ),
    _q(
        "M38",
        "Name the delivery city and the offload weekday window.",
        MULTI_HOP,
        answerable=True,
        gold_answer="Netanya; Sunday to Thursday 07:00 to 15:00",
        aliases=["Netanya", "07:00 to 15:00"],
        must_all=["Netanya", "07:00 to 15:00"],
        decisive=[
            _span(2, "Netanya"),
            _span(15, "OFFLOAD-WINDOW-0715"),
        ],
        notes="Early place + late hours.",
    ),
    # --- G. GLOBAL ---
    _q(
        "M39",
        "Summarize the complete shipment policy including any exception.",
        GLOBAL,
        answerable=True,
        gold_answer="no partial shipments except emergency orders of 200 m2 or less within 48 hours, not MW-100",
        aliases=["EXCEPTION-PARTIAL-SHIP-48H", "shall not make partial shipments"],
        must_all=["shall not make partial shipments", "EXCEPTION-PARTIAL-SHIP-48H"],
        decisive=[
            _span(5, "MAIN-RULE-NO-PARTIAL-SHIP"),
            _span(14, "EXCEPTION-PARTIAL-SHIP-48H"),
        ],
        notes="Needs main rule and later exception.",
    ),
    _q(
        "M40",
        "List every SKU that has a unit price in the agreement.",
        GLOBAL,
        answerable=True,
        gold_answer="MW-50, MW-80, MW-100",
        aliases=["MW-50", "MW-80", "MW-100"],
        must_all=["MW-50", "MW-80", "MW-100"],
        decisive=[
            _span(4, "MW-50 |"),
            _span(4, "MW-80 |"),
            _span(4, "MW-100 |"),
        ],
    ),
    _q(
        "M41",
        "Which districts have a published regional lead-time row?",
        GLOBAL,
        answerable=True,
        gold_answer="Tel Aviv District, Haifa District, Southern District",
        aliases=["Tel Aviv District", "Haifa District", "Southern District"],
        must_all=["Tel Aviv District", "Haifa District", "Southern District"],
        decisive=[_span(16, "LEADTIME-TABLE-REGIONS")],
    ),
    _q(
        "M42",
        "What identifications uniquely name this contract and the project?",
        GLOBAL,
        answerable=True,
        gold_answer="BEN-GOLD-SA-2026-001 and Netanya Logistics Annex",
        aliases=["BEN-GOLD-SA-2026-001", "Netanya Logistics Annex"],
        must_all=["BEN-GOLD-SA-2026-001", "Netanya Logistics Annex"],
        decisive=[
            _span(1, "BEN-GOLD-SA-2026-001"),
            _span(1, "Netanya Logistics Annex"),
        ],
    ),
    _q(
        "M43",
        "State the warranty length and the inspection window together.",
        GLOBAL,
        answerable=True,
        gold_answer="24 months; 7 calendar days",
        aliases=["24 months", "7 calendar days"],
        must_all=["24 months", "7 calendar days"],
        decisive=[
            _span(7, "WARRANTY-24-MONTHS"),
            _span(12, "INSPECT-7-CALENDAR-DAYS"),
        ],
    ),
    # --- H. NEGATIVE / UNANSWERABLE ---
    _q(
        "M44",
        "What is the liquidated damages rate per day of delay?",
        NEGATIVE,
        answerable=False,
        gold_answer="not established",
        decisive=[_span(8, "DELAY-NO-LD-RATE")],
        false_attractors=["5 business days"],
        notes="Delay article exists but sets no LD rate.",
    ),
    _q(
        "M45",
        "Who is the named project manager?",
        NEGATIVE,
        answerable=False,
        gold_answer="not established",
        decisive=[_span(10, "No project manager is named in this Agreement")],
        false_attractors=["Dana Levi"],
        notes="A commercial contact is named; a PM is not.",
    ),
    _q(
        "M46",
        "Does the agreement require ISO 14001?",
        NEGATIVE,
        answerable=False,
        gold_answer="not established",
        aliases=["does not mention ISO 14001"],
        decisive=[_span(6, "This Agreement does not mention ISO 14001")],
        false_attractors=["ISO 9001"],
        notes="ISO 9001 is required; 14001 is not.",
    ),
    _q(
        "M47",
        "What is the unit price for SKU MW-120?",
        NEGATIVE,
        answerable=False,
        gold_answer="not established",
        decisive=[_span(4, "PRICE-TABLE-MW50-4250")],
        false_attractors=["42.50", "61.00", "74.25"],
        notes="Table has MW-50/80/100 only.",
    ),
    _q(
        "M48",
        "What Incoterm applies to the deliveries?",
        NEGATIVE,
        answerable=False,
        gold_answer="not established",
        decisive=[],
        notes="Incoterm never appears in the source.",
    ),
    _q(
        "M49",
        "What is the Northern District standard lead time?",
        NEGATIVE,
        answerable=False,
        gold_answer="not established",
        decisive=[_span(16, "LEADTIME-TABLE-REGIONS")],
        false_attractors=["Tel Aviv District", "Haifa District", "Southern District"],
        notes="Table has three districts; Northern is absent.",
    ),
    _q(
        "M50",
        "What bank account should invoices be paid into?",
        NEGATIVE,
        answerable=False,
        gold_answer="not established",
        decisive=[_span(5, "Payment term: 30 days from invoice date")],
        false_attractors=["30 days"],
        notes="Payment timing exists; account details do not.",
    ),
]


def questions_by_id() -> dict[str, dict[str, Any]]:
    return {q["question_id"]: q for q in QUESTIONS}
